name: Best Practices Checker

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  ci_cd_check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: CI/CD Check
        run: |
            cat deployment.yml
            cat .github/workflows/checker.yml
            
            
